git clone "https://gerrit.o-ran-sc.org/r/nonrtric/plt/a1policymanagementservice" -b g-release
git clone "https://gerrit.o-ran-sc.org/r/nonrtric/plt/dmaapadapter" -b g-release
git clone "https://gerrit.o-ran-sc.org/r/nonrtric/plt/dmaapmediatorproducer" -b g-release
git clone "https://gerrit.o-ran-sc.org/r/nonrtric/plt/helmmanager" -b g-release
git clone "https://gerrit.o-ran-sc.org/r/nonrtric/plt/informationcoordinatorservice" -b g-release
git clone "https://gerrit.o-ran-sc.org/r/nonrtric/plt/rappcatalogue" -b g-release
git clone "https://gerrit.o-ran-sc.org/r/nonrtric/rapp/ransliceassurance" -b g-release
git clone "https://gerrit.o-ran-sc.org/r/nonrtric/rapp/orufhrecovery" -b g-release
     git clone "https://gerrit.o-ran-sc.org/r/nonrtric/rapp/orufhrecovery" -b g-release
     git clone "https://gerrit.o-ran-sc.org/r/nonrtric/plt/sme" -b g-release         