version: '3'

networks:
  nonrtric-docker-net:
    external: true

services:
  oru-app:
    image: "${ORU_APP_IMAGE_BASE}:${ORU_APP_IMAGE_TAG}"
    container_name: oru-app
    networks:
      - nonrtric-docker-net
    ports:
      - 8087:8087
    environment:
      - CONSUMER_HOST=http://oru-app
      - CONSUMER_PORT=8087
      - INFO_COORD_ADDR=http://information-coordinator-service:8083
      - CONSUMER_CERT_PATH=security/consumer.crt
      - CONSUMER_KEY_PATH=security/consumer.key
      - LOG_LEVEL=Debug
    volumes:
      - ./config/oru-app/o-ru-to-o-du-map.txt:/usr/src/app/o-ru-to-o-du-map.txt:ro

  odu-app:
    image: "${ODU_APP_IMAGE_BASE}:${ODU_APP_IMAGE_TAG}"
    container_name: odu-app
    networks:
      - nonrtric-docker-net
    ports:
      - 8095:8095
    environment:
      - SDNR_USER=admin
      - SDNR_PASSWORD=Kp8bJ4SXszM0WXlhak3eHlcse2gAw84vaoGGmJvUy2U
      - CONSUMER_HOST=http://odu-app
      - CONSUMER_PORT=8095
      - INFO_COORD_ADDR=http://information-coordinator-service:8083
      - SDNR_ADDR=http://192.168.122.88:3905
      - LOG_LEVEL=Trace