apiVersion: v1
entries:
  hw-go:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2023-01-26T03:40:24.539870532Z"
    description: Standard xApp Helm Chart
    digest: 114d7e5ed2e3bf5efa11418cef373ea3607aeb9e5ce8aa6eb6200de128969937
    name: hw-go
    urls:
    - charts/hw-go-1.0.0.tgz
    version: 1.0.0
  hw-python:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2023-01-26T11:26:07.614840836Z"
    description: Standard xApp Helm Chart
    digest: 39be5ae669b7319c3d0db8360f1342629a03ff70b823863ce7035f2ea5252e8e
    name: hw-python
    urls:
    - charts/hw-python-1.0.0.tgz
    version: 1.0.0
  iii-python:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2023-01-26T11:31:24.628035034Z"
    description: Standard xApp Helm Chart
    digest: 032be7024f6c8e6a304042d329ccb5662db8d21eb20cf7753d0dd0b284d04ff2
    name: iii-python
    urls:
    - charts/iii-python-1.0.0.tgz
    version: 1.0.0
generated: "2023-01-26T11:31:25Z"
serverInfo: {}
